# Generated by Django 4.0.6 on 2022-08-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Rotunda_logo.svg.png', upload_to='profile_pics'),
        ),
    ]
