# Generated by Django 4.0.6 on 2022-10-04 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housing101', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('types', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('info', models.TextField(blank=True, null=True)),
                ('advantage', models.TextField(blank=True, null=True)),
                ('disadvantage', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='Rotunda_logo.svg.png', null=True, upload_to='profile_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing101_author_offposts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
