# Generated by Django 4.0.6 on 2022-08-07 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='profile_pics')),
                ('post_category', models.CharField(choices=[('ask', 'ask'), ('bid', 'bid')], default='ask', max_length=10)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('sold', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='r_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
