# Generated by Django 4.0.6 on 2022-08-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpost',
            name='image',
            field=models.ImageField(default='No_Picture.jpeg', upload_to='profile_pics'),
        ),
    ]
