# Generated by Django 4.0.6 on 2022-08-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0002_alter_rpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpost',
            name='image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
