# Generated by Django 4.0.6 on 2022-08-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0004_alter_rpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
