# Generated by Django 4.0.6 on 2022-08-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0005_alter_rpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
