# Generated by Django 4.0.6 on 2022-08-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0006_alter_rpost_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpost',
            old_name='name',
            new_name='title',
        ),
    ]
