# Generated by Django 4.0.6 on 2022-08-10 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0012_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='date',
        ),
    ]
