# Generated by Django 4.0.6 on 2022-08-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpost',
            name='post_category',
            field=models.CharField(choices=[('ask', 'ask'), ('bid', 'bid')], default='ask', max_length=10),
        ),
    ]
