# Generated by Django 4.0.6 on 2022-08-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_hpost_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hpost',
            old_name='status',
            new_name='sold',
        ),
    ]
