# Generated by Django 4.0.6 on 2022-08-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_comment_post_delete_hpost_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
    ]
